---
title: "EDS 222: Assignment 04 (due: Dec 8th, 5pm)"
author: "Luna Herschenfeld-Catalan"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
---

```{r}
# load libraries
library(foreign)
library(tidyverse)
library(here)
library(sf)
library(terra)
library(spData)
library(geodata)
library(spDataLarge)
library(modelr)
library(ggplot2)
library(knitr)
library(broom)
```

## Read in data

- Groundwater level time series data from 1978-2018

```{r}
gw_level_total <- readxl::read_xlsx(here("data/groundwater_time_series.xlsx")) %>% 
  select(Year, WaterLevel) %>% # select years
  separate_wider_delim(col = Year, 
                       ".", # separate the months
           names = c("Year", "Month")) %>% 
  select(!Month) %>% # remove the decimal column 
  mutate_at(vars(Year), as.numeric)

# these are the mean depth to groundwater level
gw_mean <- gw_level_total %>% 
  group_by(Year) %>% 
  summarize(mean = mean(WaterLevel))
```

- Precipitation time series data from 

```{r}
precip <- readxl::read_xlsx(here("data/precip.xlsx")) %>% 
  select(!StnID) # remove column 

```

- Load in ndvi data
```{r}
ndvi_percent_aquifer <- read_csv(here("data/ag_density/ndvi_percent_aquifer.csv")) %>% 
  select(year, percent) %>% 
  rename(aq_percent_ndvi = percent)

ndvi_percent_well <- read_csv(here("data/ag_density/ndvi_percent_well_df.csv")) %>% 
  select(years, percent) %>% 
  rename(well_percent_ndvi = percent)

ndvi <- ndvi_percent_aquifer %>% 
  full_join(ndvi_percent_well, by = c("year" = "years"))
  
```


- Join Groundwater level and precip data together

```{r}
qazvin_clean <- gw_mean %>% 
  left_join(precip, by = c("Year" = "year")) %>% 
  left_join(ndvi, by = c("Year" = "year")) %>% 
  rename(level = mean,
         annual_precip = total_annual_precip)
```

# Run regression model 

```{r}
mod <- lm(level ~ annual_precip + aq_percent_ndvi, data = qazvin_clean)

summary(mod)

```

